### ISSUE TITLE
Problem using grunt-contrib-sass with build system

### ISSUE THREAD

**Issue by mackrauss** [jonschlinkert/sublime-grunt-build#3]
I am using grunt to JSHint, compile coffee script and translate SCSS into CSS with grunt-contrib-sass (https://github.com/gruntjs/grunt-contrib-sass).

Running grunt on the command line works but I like to have the build process kicked off in Sublime Text 2.

sublime-grunt-build didn't work at first until I included the following line in grunt.sublime-build

"path":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",

This now kicks of grunt and JSHint and coffee work however the SASS process fails with this error message:

unning "sass:compile" (sass) task
env: ruby_noexec_wrapper: No such file or directory
Warning: You need to have Ruby and Sass installed and in your PATH for
this task to work. More info:
https://github.com/gruntjs/grunt-contrib-sass Use --force to continue.

Not sure why it works on the cmd line and not in the Sublime Text build.

Can you help me. Do you need more information?

**Comment by jonschlinkert** [comment]
Hi @mackrauss, the path you described doesn't look right. you need to make sure that the plugin is copied into a folder in the Sublime Text packages folder. The best way to make sure you're in the correct folder is to open the folder from Sublime Text, as in the instructions. Just go to `preferences > browse packages` and that will open up the folder. 

My other recommendation would be to use `grunt-contrib-watch` instead. That's actually what I've been using myself

**Comment by mackrauss** [comment]
Think I figured it out. I had to add a file that makes sure Sublime knows about the paths in the correct way. I took the path I added to grunt.sublime-build out and added the following file:

~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Pathway.py

import os

LOCAL = '/usr/local/bin:/usr/local/sbin:'
HOME = '/Users/armin'
RVM = HOME + '/.rvm/bin:'
#RVM = HOME + '/.rvm/gems/ruby-1.9.3-p194/bin:'

# Sublime's default path is

# /usr/bin:/bin:/usr/sbin:/sbin

os.environ['PATH'] += ':'
os.environ['PATH'] += LOCAL
os.environ['PATH'] += RVM

print 'PATH = ' + os.environ['PATH']

Also I was using RVM on my Mac and set it to use the system Ruby. Installed SASS with the standard Ruby and now command+B allows me to save everything and build with grunt :)

Thanks for creating this extension and be so welcoming and helpful.

**Comment by jonschlinkert** [comment]
No problem, glad it has been useful.
