### ISSUE TITLE
Call grunt tasks.

### ISSUE THREAD

**Issue by Chris2011** [jonschlinkert/sublime-grunt-build#6]
Hi,

what about to call other tasks like grunt server, server:dist, test or anything else inside of sublime text 2? As I see, only build is possible?

Regards

Chris

**Comment by jonschlinkert** [comment]
if you put a pull request together I'd be happy to merge it in. I'd be happy to do it, but it might take me a while to get around to doing it.

**Comment by Chris2011** [comment]
If I have time I will clone your repo and will take a look to the code to implement such things :). Thanks for the reply.

**Comment by jonschlinkert** [comment]
:+1:

**Comment by Chris2011** [comment]
Due to lack of time and not using Sublime Text 2 I will close the ticket. For me it is not needed anymore. Sry :(
